//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfaceDemo
{
    public interface IBolt  : ITightenable, IPart
    {
        string UnitSystem { get;set; }

        float Length { get;set; }

        string HeadType { get;set; }

        float Diameter { get;set; }

    }
}

