//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace InterfaceDemo
{
    public interface IComplexPart  : IPart
    {
        IList<IPart> Parts { get;set; }

    }
}

